services:
  - type: web
    name: ai-job-assistant-backend
    runtime: python
    rootDir: backend
    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      pip install --only-binary=:all: -r requirements.txt || pip install -r requirements.txt
      python -c "import nltk; nltk.download('stopwords', quiet=True); nltk.download('punkt', quiet=True)"
      mkdir -p utils/output
    startCommand: cd app && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PIP_NO_CACHE_DIR
        value: "1"
    healthCheckPath: /health
    plan: free
    region: oregon

  - type: web
    name: ai-job-assistant-frontend
    runtime: python
    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      pip install --only-binary=:all: -r requirements.txt || pip install -r requirements.txt
    startCommand: streamlit run frontend/streamlit_app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true --server.enableCORS false --server.enableXsrfProtection false
    envVars:
      - key: API_BASE_URL
        value: https://ai-job-assistant-backend.onrender.com
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PIP_NO_CACHE_DIR
        value: "1"
    plan: free
    region: oregon
